language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - jari@holderdeord.no
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
script: "RAILS_ENV=test bundle exec rake travis"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g buster autolint"
env:
  - DISPLAY=:99.0 COVERAGE_THRESHOLD=75
