defaults: &defaults
  issue_editing_enabled: true
  front_page_search_enabled: true
  elasticsearch_url: http://localhost:9200
  statsd_host: localhost
  statsd_port: 8125
  statsd_enabled: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
