defaults: &defaults
  issue_editing_enabled: true
  front_page_search_enabled: true
  elasticsearch_url: http://localhost:9200
  statsd_host: 5.9.122.47 # ops1.holderdeord.no, but avoid DNS lookup
  statsd_port: 8125
  statsd_enabled: false
  analytics_enabled: false
  ignore_votes_against_alternate_budget: false
  ignore_votes_against_proposal_attached_to_minutes: false

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  statsd_enabled: true
  ignore_votes_against_alternate_budget: true

production:
  <<: *defaults
  analytics_enabled: true
  ignore_votes_against_alternate_budget: false
  ignore_votes_against_proposal_attached_to_minutes: false
