defaults: &defaults
  read_only: false
  front_page_search_enabled: true
  elasticsearch_url: <%= ENV['ELASTICSEARCH_URL'] || ENV['BONSAI_URL'] || 'http://localhost:9200' %>
  fastly_enabled: false
  statsd_host: 5.9.122.47 # ops1.holderdeord.no, but avoid DNS lookup
  statsd_port: 8125
  statsd_enabled: false
  ssl_enabled: false
  ssl_host: ~
  analytics_enabled: false
  questions_enabled: true
  answers_enabled: true
  show_accountability: true
  widgets_enabled: true
  representative_widget_enabled: true
  leaderboard_enabled: true
  ignore_our_questions: true
  ssl_enabled: false
  ssl_host: ~
  default_bcc_email: test@holderdeord.no
  default_reply_to_email: kontakt@holderdeord.no

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  statsd_enabled: true
  fastly_enabled: true
  ssl_enabled: true

production:
  <<: *defaults
  analytics_enabled: true
  questions_enabled: true
  answers_enabled: false
  representative_widget_enabled: false
  fastly_enabled: true
  ssl_enabled: true
  leaderboard_enabled: false
