defaults: &defaults
  issue_editing_enabled: true
  front_page_search_enabled: true
  elasticsearch_url: http://localhost:9200

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults